#!/usr/bin/env node
// Bundles the two scripts that run on the runner — src/main.js (action.yml
// `main:`) and mvn-lens/attach.js (the composite step) — together with their
// npm dependencies into dist/, so the action needs no `npm install` at run
// time. dist/ is committed; CI fails when it is stale
// (`npm run build && git diff --exit-code -- dist`).
'use strict';
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const root = path.join(__dirname, '..');
const ENTRIES = [
  { in: 'src/main.js', out: 'index' },         // action.yml:          main: dist/index.js
  { in: 'mvn-lens/attach.js', out: 'attach' }, // mvn-lens/action.yml: node dist/attach.js
];

async function main() {
  const outdir = path.join(root, 'dist');
  fs.rmSync(outdir, { recursive: true, force: true });
  const result = await esbuild.build({
    absWorkingDir: root,
    entryPoints: ENTRIES,
    outdir: 'dist',
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    minify: false,          // the bundle is what runs with the user's token: keep it readable
    sourcemap: false,
    legalComments: 'inline',
    logLevel: 'warning',
    metafile: true,
    banner: { js: '// Generated by `npm run build` (esbuild) from src/ and mvn-lens/ — do not edit, change the sources and rebuild.' },
  });
  // dist/ sits at the same depth as src/, so `path.join(__dirname, '..')` in the
  // sources keeps resolving to the repository root (package.json, site/).

  // Third-party notices for everything that ended up in the bundles.
  const pkgs = new Map();
  for (const input of Object.keys(result.metafile.inputs)) {
    const m = /^node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(input.replace(/\\/g, '/'));
    if (m) pkgs.set(m[1], path.join(root, 'node_modules', m[1]));
  }
  const lines = [
    'Third-party packages bundled into dist/index.js and dist/attach.js.',
    'Generated by scripts/build.js; the action itself is Apache-2.0 (see ../LICENSE, ../NOTICE).',
    '',
  ];
  for (const [name, dir] of [...pkgs.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    const licFile = fs.readdirSync(dir).find(f => /^licen[cs]e/i.test(f));
    lines.push('='.repeat(78), `${name}@${pkg.version} — ${pkg.license || 'license not declared'}${pkg.homepage ? ' — ' + pkg.homepage : ''}`, '='.repeat(78), '');
    lines.push(licFile ? fs.readFileSync(path.join(dir, licFile), 'utf8').trim() : '(no license file in the package; see the "license" field of its package.json)', '');
  }
  fs.writeFileSync(path.join(outdir, 'licenses.txt'), lines.join('\n') + '\n');

  for (const e of ENTRIES) {
    const f = path.join(outdir, e.out + '.js');
    console.log(`${e.in} -> dist/${e.out}.js  ${Math.round(fs.statSync(f).size / 1024)} KB`);
  }
  console.log(`dist/licenses.txt  ${pkgs.size} package(s): ${[...pkgs.keys()].sort().join(', ')}`);
}

main().catch(e => { console.error(e && e.stack ? e.stack : String(e)); process.exit(1); });
